const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..');
function load(hostId,seed){let click;const values=new Map(Object.entries(seed||{})),host={innerHTML:'',getClientRects(){return[{}];},querySelector(){return null;},addEventListener(name,fn){click=fn;}};const window={document:{hidden:false,getElementById(id){return id===hostId?host:null;},addEventListener(){}},localStorage:{getItem(k){return values.has(k)?values.get(k):null;},setItem(k,v){values.set(k,v);},removeItem(k){values.delete(k);}},requestAnimationFrame(){},addEventListener(){}};for(const file of ['campaign-core','salvage-expedition','echo-deck','relay-defense'])vm.runInNewContext(fs.readFileSync(path.join(root,'src',file+'.js'),'utf8'),{window,console});return{window,values,host,act(dataset){click({target:{closest(){return{dataset};}}});}};}
const models=load().window,S=models.XXSXSalvage,D=models.XXSXEchoDeck,R=models.XXSXRelayDefense;
function test(name,fn){fn();console.log('✓ '+name);}
function go(s,to){const blocked=S.layouts[s.deck],queue=[[s.pos]],seen=new Set([s.pos]);let route;while(queue.length){const p=queue.shift(),last=p[p.length-1];if(last===to){route=p;break;}for(let next=0;next<25;next++){if(seen.has(next)||blocked[next]==='#'||blocked[next]==='G'&&!s.cleared[s.deck].includes(next))continue;if(Math.abs(last%5-next%5)+Math.abs(Math.floor(last/5)-Math.floor(next/5))!==1)continue;seen.add(next);queue.push(p.concat(next));}}assert.ok(route,'reachable '+to);for(const step of route.slice(1)){assert.equal(S.move(s,step),true);assert.equal(s.pos,step);assert.equal(s.phase,'explore');assert.equal(S.valid(s),true);}}
test('salvage supports a legal three-deck core recovery with finite resources',()=>{const s=S.create(12,'engineer');for(let deck=0;deck<2;deck++){go(s,deck===0?0:8);const item=s.ground[s.deck].find(i=>i.cell===s.pos);assert.equal(S.act(s,'take',{item:item.id}),true);go(s,deck===0?2:10);go(s,4);S.act(s,'descend',{});assert.equal(s.phase,'upgrade');S.act(s,'upgrade',{choice:deck===0?'cargo':'seal'});assert.equal(S.valid(s),true);}go(s,17);go(s,14);const core=s.ground[2].find(i=>i.kind==='core');S.act(s,'take',{item:core.id});go(s,24);S.act(s,'extract',{});assert.equal(s.phase,'won');assert.ok(s.oxygen>0);assert.ok(S.score(s)>=700);assert.equal(S.act(s,'extract',{}),false);});
test('cargo weight, capacity, guard alternatives and heat have real costs',()=>{const s=S.create(2,'scout');go(s,10);const data=s.ground[0].find(i=>i.cell===10);S.act(s,'take',{item:data.id});go(s,7);assert.equal(S.act(s,'hack',{cell:'12'}),true);assert.equal(s.tools,2);assert.equal(s.hp,80);go(s,12);assert.equal(s.pos,12);const b=S.create(2,'engineer');go(b,7);S.act(b,'breach',{cell:'12'});assert.equal(b.hp,72);assert.equal(b.heat,2);const weighed=S.create(1,'hauler');weighed.bag=[{id:'0-0',kind:'relic',cell:0},{id:'0-10',kind:'relic',cell:10}];assert.equal(S.cost(weighed),3);weighed.heat=5;assert.equal(S.cost(weighed),5);const weightBefore=S.weight(weighed);S.act(weighed,'drop',{item:'0-0'});assert.equal(S.weight(weighed),weightBefore-3);
});
test('salvage refuses remote moves and loses cargo value when oxygen is exhausted',()=>{const s=S.create(3,'hauler');assert.equal(S.move(s,0),false);s.oxygen=1;assert.equal(S.move(s,21),true);assert.equal(s.phase,'lost');assert.equal(S.score(s),0);assert.equal(S.act(s,'extract',{}),false);});
test('card energy, focusing and echo resolve in order and persist legal card zones',()=>{const s=D.create(1,'resonance');D.battle(s,false);s.draw=s.deck.map(c=>c.id);s.hand=[];s.discard=[];for(const kind of ['focus','strike','echo']){const id=s.draw.find(id=>s.deck.find(c=>c.id===id).kind===kind);s.draw.splice(s.draw.indexOf(id),1);s.hand.push(id);}const before=s.enemies[0].hp;for(const id of s.hand.slice())assert.equal(D.play(s,id),true);assert.equal(s.energy,0);assert.equal(s.enemies[0].hp,before-30);assert.equal(D.valid(s),true);});
test('shield blocks announced damage and patch is exhausted for the battle',()=>{const s=D.create(8,'bulwark');D.battle(s,false);const shield=s.deck.find(c=>c.kind==='guard').id,patch=s.deck.find(c=>c.kind==='patch').id;for(const id of [shield,patch]){let i=s.draw.indexOf(id);if(i>=0)s.draw.splice(i,1);if(!s.hand.includes(id))s.hand.push(id);}s.hp=60;assert.equal(D.play(s,shield),true);assert.equal(D.play(s,patch),true);assert.equal(s.hp,66);assert.ok(s.exhaust.includes(patch));D.endTurn(s);assert.equal(s.hp,66);assert.equal(D.valid(s),true);});
test('research removal does not leave stale references and battle rewards cannot repeat',()=>{const s=D.create(4);s.stage=1;s.phase='camp';s.coins=100;const card=s.deck[0];assert.equal(D.act(s,'remove',{card:String(card.id)}),true);assert.equal(s.deck.length,9);assert.equal(D.valid(s),true);assert.equal(D.act(s,'remove',{card:String(card.id)}),false);s.phase='reward';s.offers=['draw','mark','shred'];D.act(s,'reward',{choice:'shred'});assert.equal(s.deck.length,10);assert.equal(D.valid(s),true);assert.equal(D.act(s,'reward',{choice:'shred'}),false);});
test('tower construction consumes funds, upgrades cap, selling refunds only invested funds',()=>{const s=R.create(5,'0');assert.equal(R.act(s,'build',{choice:'pulse'}),true);assert.equal(s.credits,68);assert.equal(R.act(s,'build',{choice:'pulse'}),false);assert.equal(R.act(s,'upgradeTower',{}),true);assert.equal(s.credits,30);assert.equal(s.towers[0].level,2);R.act(s,'sell',{});assert.equal(s.credits,79);assert.equal(s.towers[0],null);});
test('fully absorbed hits cannot damage hull, split kills create two children and boss surges once',()=>{const s=R.create(7);s.wave=3;const shield=R.spawn(s,'shielded',0,2),hp=shield.hp;R.hurt(s,shield,12);assert.equal(shield.hp,hp);assert.equal(shield.shield,13);const split=R.spawn(s,'split',0,3);R.hurt(s,split,1000);assert.equal(s.enemies.filter(e=>e.kind==='mini').length,2);const boss=R.spawn(s,'boss',0,4);R.hurt(s,boss,boss.maxHp*.7,0);assert.equal(boss.surge,true);const n=s.enemies.length;R.hurt(s,boss,1,0);assert.equal(s.enemies.length,n);});
test('an undefended map loses and pause freezes simulation',()=>{const s=R.create(2);R.startWave(s);const before=s.clock;s.paused=true;R.tick(s,.5);assert.equal(s.clock,before);s.paused=false;for(let i=0;i<3000&&s.phase==='wave';i++)R.tick(s,.1);assert.equal(s.core,14);assert.equal(s.phase,'build');while(s.phase==='build'){R.startWave(s);for(let i=0;i<5000&&s.phase==='wave';i++)R.tick(s,.1);if(s.phase==='upgrade')R.act(s,'network',{choice:s.offers[0]});}assert.equal(s.phase,'lost');});
function defensePolicy(map){const s=R.create(123+map,String(map)),order=[1,3,5,0,4,2],types={0:'ion',1:'pulse',2:'cannon',3:'cannon',4:'pulse',5:'pulse'};let steps=0;while(s.phase!=='won'&&s.phase!=='lost'&&steps++<50000){if(s.phase==='build'){for(const i of order){R.act(s,'site',{site:String(i)});if(!s.towers[i])R.act(s,'build',{choice:types[i]});}for(let level=1;level<=2;level++)for(const i of order){R.act(s,'site',{site:String(i)});if(s.towers[i]&&s.towers[i].level===level)R.act(s,'upgradeTower',{});}R.startWave(s);}else if(s.phase==='upgrade'){R.act(s,'network',{choice:s.offers.includes('fund')?'fund':s.offers.includes('range')?'range':s.offers[0]});}else{if(s.capacitors>0&&s.enemies.some(e=>e.progress>10&&e.shield>0))R.act(s,'emp',{});R.tick(s,.1);if(steps%100===0)assert.equal(R.valid(s),true);}}return s;}
test('all three defense maps have a twelve-wave legal build-and-upgrade win path',()=>{for(let map=0;map<3;map++){const s=defensePolicy(map);assert.equal(s.phase,'won','map '+map+' core '+s.core+' wave '+s.wave);assert.equal(s.wave,12);assert.equal(R.valid(s),true);}});
function cardPolicy(seed,kit){let s=D.create(seed,kit),steps=0;const clone=x=>JSON.parse(JSON.stringify(x));while(!['won','lost'].includes(s.phase)&&steps++<200){if(s.phase==='route')D.act(s,'route',{choice:'battle'});else if(s.phase==='camp'){if(s.hp<s.maxHp-12&&s.coins>=10)D.act(s,'heal',{});else{const card=s.deck.find(c=>c.level===0&&D.cards[c.kind].damage);if(card&&s.coins>=18)D.act(s,'upgrade',{card:String(card.id)});else D.act(s,'rest',{});}}else if(s.phase==='reward'){const ranked=['drain','counter','shred','draw','capacitor','mark','burst','echo','patch','focus'];const choice=ranked.find(k=>s.offers.includes(k));if(s.deck.length>=12)D.act(s,'skip',{});else D.act(s,'reward',{choice});}else if(s.phase==='relic'){const choice=['battery','recovery','amp','memory'].find(k=>s.offers.includes(k));D.act(s,'relic',{choice});}else{const original=s,initialHp=s.enemies.reduce((n,e)=>n+e.hp,0),score=x=>x.phase==='won'||['reward','relic'].includes(x.phase)?1000+x.hp*2:x.phase==='lost'?-10000:(initialHp-x.enemies.reduce((n,e)=>n+e.hp,0))+x.hp*2+(original.enemies.filter(e=>e.hp>0).length-x.enemies.filter(e=>e.hp>0).length)*25;let frontier=[s],best=null,bestScore=-Infinity;for(let depth=0;depth<6&&frontier.length;depth++){const next=[];for(const node of frontier){const ended=clone(node);if(ended.phase==='battle')D.endTurn(ended);const value=score(ended);if(value>bestScore){best=ended;bestScore=value;}if(node.phase!=='battle')continue;const used=new Set();for(const id of node.hand){const c=node.deck.find(c=>c.id===id),tag=c.kind+c.level;if(used.has(tag)||D.cards[c.kind].cost>node.energy||c.kind==='echo'&&(!node.last||node.sealed>0))continue;used.add(tag);for(const target of node.enemies.filter(e=>e.hp>0)){const candidate=clone(node);candidate.target=target.id;if(D.play(candidate,id))next.push(candidate);}}}frontier=next.sort((a,b)=>score(b)-score(a)).slice(0,24);}s=best;assert.ok(s);assert.equal(D.valid(s),true);}}return s;}
test('card campaign supports a full legal nine-node clear with announced-intent planning',()=>{for(const kit of ['resonance','bulwark','phase']){const s=cardPolicy(713,kit);assert.equal(s.phase,'won',kit+' failed at stage '+s.stage+' hp '+s.hp);assert.equal(s.stage,8);}});
test('each new game saves real actions and restores its own state after reload',()=>{for(const [host,key,choice,action] of [['salvageExpedition','xxsxSalvageExpeditionV1','scout',{campaignAction:'move',cell:'21'}],['echoDeck','xxsxEchoDeckV1','phase',{campaignAction:'route',choice:'battle'}],['relayDefense','xxsxRelayDefenseV1','0',{campaignAction:'build',choice:'pulse'}]]){const session=load(host);session.act({campaignAction:'start',choice});session.act(action);const raw=session.values.get(key);assert.ok(raw);const restored=load(host,Object.fromEntries(session.values));assert.equal(restored.values.get(key),raw);assert.ok(restored.host.innerHTML.includes(host==='echoDeck'?'回合':host==='relayDefense'?'炮位':'氧气'));}});
test('malformed saves retain original bytes before replacement and checkpoints recover a valid backup',()=>{const key='xxsxSalvageExpeditionV1',s=load('salvageExpedition',{[key]:'{bad'});assert.equal(s.values.get(key),'{bad');s.act({campaignAction:'start',choice:'scout'});assert.equal(s.values.get(key+'.rejected'),'{bad');s.act({campaignAction:'move',cell:'21'});const backup=s.values.get(key+'.backup');s.values.set(key,'{broken');const r=load('salvageExpedition',Object.fromEntries(s.values));assert.match(r.host.innerHTML,/恢复上一份有效存档/);assert.equal(r.values.get(key+'.backup'),backup);r.act({campaignAction:'move',cell:'21'});assert.equal(r.values.get(key+'.rejected'),'{broken');});
test('changing a run is explicit, cancel keeps the old checkpoint and empty extraction earns no clear',()=>{const key='xxsxSalvageExpeditionV1',t=load('salvageExpedition');t.act({campaignAction:'start',choice:'scout'});t.act({campaignAction:'move',cell:'21'});const before=t.values.get(key);t.act({campaignAction:'restartPrompt'});assert.match(t.host.innerHTML,/选择新方案会重新开局/);t.act({campaignAction:'cancelRestart'});assert.equal(t.values.get(key),before);t.act({campaignAction:'restartPrompt'});t.act({campaignAction:'start',choice:'hauler'});assert.equal(JSON.parse(t.values.get(key)).state.kit,'hauler');t.act({campaignAction:'extract'});assert.equal(JSON.parse(t.values.get(key)).meta.clears,0);});
test('malformed card IDs, impossible maps and excessive cargo are rejected',()=>{let s=S.create(1);s.bag=[{id:'0-0',kind:'core',cell:0}];s.cap=1;assert.equal(S.valid(s),false);let d=D.create(2);D.battle(d,false);d.hand.push(d.hand[0]);assert.equal(D.valid(d),false);let r=R.create(4);r.map=99;assert.equal(R.valid(r),false);});
console.log('New campaign gameplay, progression and archive checks passed');
